String[] poems = {
  "I am too often calling out to the void. People take its mantle", 
  "And so I wished for it all and that was my fault", 
  "Today I ask for rice and spice", 
  "Big fat crush", 
  "It’s unfortunate but it is", 
  "I’m making myself believe that life is now too tragic to have", 
  "A lot of love for someone who gives me a lot of stress", 
  "It is a beautifully tragic thing to be human", 
  "I’ve fallen real hard this time but I think for good", 
  "All I’ve could have been, throw that out the window", 
  "How do I take care of myself", 
  "a way to describe one self in an unconventional brief way: (location of primary residence) (gender)", 
  "Contrast creates form. A shadow contextualizes an object. I am interested in objects. I was only attracted to you because of the shadow you left behind.", 
  "a breath of heavy air", 
  "I think about all that it must have taken to get to where you are now. What compelled you towards love", 
  "Describing sounds/genres as theses", 
  "A smell, a taste; the human limestone, an existence that brings all the enthrall, and yet pushes me so slightly away. Like drinking lake water; not the best but it won’t kill you that fast. Is that who you are?", 
  "How do we have stronger discussions about what we tell ourselves is something we embrace and are passionate about? What do we do to delve deeper than what is easy to say?", 
  "To all who took care of me", 
  "To all who I wish took care of me", 
  "Today (10/27) is a beautiful day and I’m reminded of Eu but this is you and this is new", 
  "What is it even that we want", 
  "Oh yeah have to go and text back some people", 
  "Something as simple as considering the human condition", 
  "They’re not all there for you", 
  "What I do to keep this body in structure and from falling apart", 
  "Grad students are our friendz", 
  "the terminal needs to be my friend, right now it's an acquaintance", 
  "What if I had just gone to an art school", 
  "All fingers except for engagement", 
  "Go out and have some fun; go out on a date, with myself or with you, I’m enjoying myself", 
  "Here now so I can do better and be myself", 
  "And so it’s like, not even enough time to breathe and we receive all of this in life, all that we never foresaw, whether or not it is good or bad, within seconds when our words leave our mouth we inherit all that was contradictory to what we assume", 
  "And so I wonder what it is that I have this peculiar luck of the draw that neither is good nor bad. A sort of good chance that ends up always at odds with misfortune", 
  "Who do we decide to extend our care and concern toward?", 
  "Is the quest for love hopelessly painful and often fatal?", 
  "I want to learn and teach too late", 
  "In lieu of a community we are born from, we grow to make our own", 
  "A bunch of hurt but I was decided right here", 
  "I’m in outsider even in the communities I belong to", 
  "First the web then the app then the", 
  "A rush of melancholy sweeps through", 
  "it feels there's too many things to catch myself up on. too many slack channels", 
  "In lieu of a community, we create our own, where we still don’t belong", 
  "Of concern and care but instead I felt profit, proprietary, and self-interest", 
  "I want to feel so grateful and to trust but you said “ya lol”", 
  "Even in my pursuit for community so far there’s someone who doesn’t", 
  "I am revisited but no unfair nor agonizing pain comes with this. I feel some melancholy because nothing in the world would have allowed me to have any say in the final decision. I had no control no matter what and it just happened because circumstance decided it so. Alignment of it all in place has always been difficult and almost impossible. And so I am unexpectedly revisted and provided a fill of regret, even though nothing I would have done could justifiably make me regretful.", 
  "Wait why do I care", 
  "the eclipse doesn't mind me. for there is a hole in my chest anyways", 
  "I can’t even imagine being remembered by you but now you’re having me remember you", 
  "I have a lot of life to live so I'll be there", 
  "I don’t want to dream or nightmare", 
  "I can’t help but hurt", 
  "Just what needs to be done", 
  "re: means regarding", 
  "It’s good to know people", 
  "The importance of .txt files", 
  "The importance of dot files", 
  "Is idolatry a sin? All I want are mentors", 
  "In love? That shit is insane", 
  "A feeling of defeat a feeling of want", 
  "Who am I being saved for", 
  "And with that, the word", 
  "And with that, the truth", 
  "And with that, reality", 
  "For what I have given, do I deserve", 
  "And yes, no one", 
  "No time to be denied", 
  "Least deserving, most receiving", 
  "Kinda bored", 
  "Why am I full of tears", 
  "No one may mistreat me!", 
  "Will grad school save you?", 
  "How do I take care of myself"
};
