PFont font;

String[] phrases = {
"I think and wonder",
"what can we do to",
"bring solution?",
"Am I my brother's keeper?",
"Community organizing",
"People need to",
"get paid",
"Why force",
"anything",
"what is useful vs scalable",
"How do we let these people invade our dreams?",
"Hijack our emotions",
"and dictate how we feel and",
"perceive?",
"Without so much as having",
"a single conversation with us,",
"they can decide who we are",
"without even knowing our names.",
"the images we make",
"inside ourselves",
"have the power to",
"create change outside",
"of our bodies",
"Take a stab at",
"the childish",
"What is life and",
"who has a right to it",
"Intraethnic dating vs",
"vs racial fetishism",
"Filtering our source of stimulus,",
"we have the ability to",
"choose what to be said;",
"what is amplified and",
"what is constrained",
"a way to describe",
"one self",
"in an unconventional brief way:",
"(location of primary residence) (gender)",
"e.g. tokyo woman, new york man, london nonbinary, etc",
"Contrast creates form.",
"A shadow contextualizes an object.",
"I am interested in objects.",
"I was only attracted to",
"you because of",
"the shadow you left behind.",
"a breath of heavy air",
"I think about",
"all that it must have taken",
"to get to where you are now.",
"What compelled you",
"towards love",
"I guess I’m",
"just interested in",
"making friends",
"and participating in a community",
"that has since been absent!",
"There is such thing as",
"a sustainability of data.",
"The ability to inundate the web with",
"unfettered shit doesn’t warrant the ability to",
"disregard mindful and appropriate usage of the web ",
"What’s so weird",
"Describing sounds/genres as",
"theses ",
"Ain’t it fun just to",
"meet people anyways?",
"What’s with",
"networking",
"Does leverage and credence and weight of opinion",
"invoke a student to take serious the word of",
"a teacher?",
"Is it simply mutual respect?",
"A smell, a taste; the human limestone,",
"an existence that brings all the enthrall,",
"and yet pushes me so slightly away.",
"Like drinking lake water;",
"not the best but",
"it won’t kill you that fast.",
"Is that who you are?",
"How do we have",
"stronger discussions about what we",
"tell ourselves is something",
"we embrace and are passionate about?",
"What do we do to",
"delve deeper than what is",
"easy to say?",
"To all who took care of me",
"To all who I wish took care of me",
"Today is a",
"beautiful day",
"I’m reminded of Eu",
"but this is you",
"and this is new",
"What is it",
"even that we want",
"Oh yeah have to go",
"text back some people",
"Is that a weird thing?",
"I’m falling slowly for",
"art",
"Something as simple as",
"considering the human",
"condition",
"Systems thinking",
"They’re not all there",
"for you",
"What I do to keep this body",
"in structure and from falling apart",
"Being able to be fine with",
"the image that appears in a video chat",
"that is supposed to represent me",
"is a place I have always wanted to be",
"we’re very close!!!!!",
"Grad students are our friendz",
"the terminal needs to be my friend,",
"right now it's an acquaintance",
"flatten the hierarchy",
"everyone is your friend.",
"what about your brother/sister",
"i would like to try to be everyone's",
"brother and i would like to try",
"for everyone to be someone i cared for.",
"Yeah gotta fight for shit",
"to happen",
"What if I had",
"just gone to an art school",
"All fingers",
"except for engagement",
"Go out and have some fun;",
"go out on a date,",
"with myself or with you,",
"I’m enjoying myself",
"If we can't date",
"can we be friends,",
"your company is fun enough",
"Here now so I can do better",
"and be myself",
"And so it’s like,",
"not even enough time to breathe",
"and we receive all of this in life,",
"all that we never foresaw,",
"whether or not it is good or bad,",
"within seconds",
"when our words leave",
"our mouth we inherit all",
"that was contradictory to",
"what we assume",
"And so I wonder",
"what it is that",
"I have this peculiar luck",
"of the draw that neither is good nor bad.",
"A sort of good chance that",
"ends up always at odds with misfortune",
"Who do we decide to",
"extend our care",
"and concern toward?",
"Is the quest for love",
"hopelessly painful",
"and often fatal?",
"I want to learn",
"and teach",
"too late",
"In lieu of a",
"community we are born from,",
"we grow to make our own",
"PDF as",
"performance",
"Rethinking the value of an art",
"education/a new strategy for how",
"an art education is generally perceived",
"A bunch of hurt but",
"I was decided right here",
"How do I begin trusting",
"Google and how do I begin trusting",
"monopolies and",
"how do I begin trusting",
"I’m in outsider even in",
"the communities I belong to",
"The syllabus as",
"performance",
"First the web then the",
"app then the",
"My impression is that",
"many art galleries even today gravitate often to",
"I guess the more analog of digital;",
"CRT TVs, old Dells from the 80s.",
"I gravitate toward them too and",
"I’m not sure why",
"Even if I/we don’t intend for",
"what warrants it,",
"a tinge of jealousy always appears",
"when I am left for another",
"What’s the point of art",
"it feels there's too many",
"things to catch myself up on.",
"too many slack channels",
"A rush of melancholy sweeps through",
"In lieu of a community,",
"we create our own,",
"where we still don’t belong",
"Of concern and care",
"but instead I felt",
"profit, proprietary, and self-interest",
"I want to feel so grateful and to",
"trust",
"but you said “ya lol”",
"Even in my pursuit for",
"community so far there’s",
"someone who doesn’t",
"I am revisited but",
"no unfair nor agonizing pain comes with",
"this. I feel some melancholy",
"because nothing in the world would",
"have allowed me to have any",
"say in the final decision.",
"I had no control",
"no matter what",
"and it just happened because",
"circumstance decided it so.",
"Alignment of it all in place has",
"always been difficult and almost impossible.",
"And so I am unexpectedly revisted",
"and provided a fill of regret,",
"even though nothing I would have done",
"could justifiably make",
"me regretful.",
"Wait why do I care",
"the eclipse doesn't mind me.",
"for there is a hole in my chest anyways",
"I can’t even imagine",
"being remembered by you",
"but now you’re",
"having me remember you",
"I have a lot of life",
"to live so I'll be there",
"I don’t want to dream or",
"nightmare",
"I can’t help but hurt",
"Just what needs to be done",
"re: means regarding",
"It’s good to know people",
"The importance of .txt files",
"The importance of dot files",
"Is idolatry a sin?",
"All I want are mentors",
"In love?",
"That shit is insane",
"Content Management",
"Program Management",
"Knowledge Management",
"A feeling of defeat",
"a feeling of want",
"Who am I being saved for",
"And with that, the word",
"And with that, the truth",
"And with that, reality",
"For what I have given,",
"do I deserve",
"And yes, no one",
"Shit I do",
"for our department!!!!",
"No time to be denied",
"Least deserving, most receiving",
"Kinda bored",
"No one knows who I am.",
"Kinda neat",
"Someone stands by shyly.",
"They hope to join in",
"on this conversation you're in.",
"You invite them",
"maybe by saying",
"with earnest conern and consideration,",
"Oh would you like to",
"join in on our conversation?",
"Why am I full of tears",
"No one may mistreat me!",
"Will grad school",
"save you?",
"How do I take care",
"of myself",
"All I’ve could have been,",
"throw that out the window",
"I’ve fallen real hard",
"this time",
"but I think for good",
"Maybe the problem is",
"that people are attaching value",
"that may fundamentally not exist",
"but not even doing",
"the proper homework",
"to at least try",
"and make it exist",
"It’s okay",
"make something out of",
"nothing but not do your homework",
"and maybe that’s just it",
"people are not doing their homework ",
"Why is the pursuit for love",
"one you joke against?",
"Why aren’t you nice and",
"what did you do to deserve the best?",
"All I could ask for",
"It is a beautifully tragic thing to",
"be human",
"If we are not human",
"what is a better way to describe us",
"that also is inclusive",
"of our human ancestors?",
"Is there a term that",
"encapsulates all of that?",
"A lot of love",
"for someone who gives me a lot of stress",
"I’m making myself",
"believe that life is now too tragic",
"to have",
"Good old pain",
"It’s unfortunate",
"but it is",
"I need to go see Elephant Gym live now",
"Big fat crush"
};
