PFont font;

String[] indp = {
    "I think and wonder",
    "Am I my brother's keeper?",
    "Community organizing",
    "anything",
    "what is useful vs scalable",
    "How do we let these people invade our dreams?",
    "a single conversation with us,",
    "they can decide who we are",
    "the images we make",
    "inside ourselves",
    "create change outside",
    "of our bodies",
    "the childish",
    "a way to describe",
    "one self",
    "e.g. tokyo woman, new york man, london nonbinary, etc",
    "A shadow contextualizes an object.",
    "I am interested in objects.",
    "Contrast creates form.",
    "a breath of heavy air",
    "a sustainability of data.",
    "networking",
    "Is it simply mutual respect?",
    "A smell, a taste; the human limestone,",
    "Is that who you are?",
    "Is that a weird thing?",
    "Systems thinking",
    "we’re very close!!!!!",
    "considering the human",
    "All fingers",
    "the image that appears in a video chat",
    "can we be friends,",
    "your company is fun enough"
};

String[] start = {
    "What do we do to",
"what can we do to",
"People need to",
"Why force",
"Hijack our emotions",
"and dictate how we feel and",
"Without so much as having",
"without even knowing our names.",
"have the power to",
"Take a stab at",
"What is life and",
"Intraethnic dating vs",
"Filtering our source of stimulus,",
"we have the ability to",
"what is amplified and",
"what is constrained",
"in an unconventional brief way:",
"choose what to be said;",
"I was only attracted to",
"you because of",
"I think about",
"What compelled you",
"I guess I’m",
"There is such thing as",
"The ability to inundate the web with",
"What’s so weird",
"Describing sounds/genres as",
"Ain’t it fun just to",
"What’s with",
"Does leverage and credence and weight of opinion",
"unfettered shit doesn’t warrant the ability to",
"Like drinking lake water;",
"How do we have",
"an existence that brings all the enthrall,",
"stronger discussions about what we",
"tell ourselves is something",
"Something as simple as",
"To all who took care of me",
"To all who I wish took care of me",
"Today is a",
"I’m reminded of Eu",
"Oh yeah have to go",
"What is it",
"I’m falling slowly for",
"They’re not all there",
"What I do to keep this body",
"Being able to be fine with",
"the terminal needs to be my friend,"
};

String[] end = {
"bring solution?",
"get paid",
"perceive?",
"who has a right to it",
"vs racial fetishism",
"the shadow you left behind.",
"all that it must have taken",
"to get to where you are now.",
"towards love",
"just interested in",
"making friends",
"and participating in a community",
"that has since been absent!",
"disregard mindful and appropriate usage of the web ",
"theses",
"meet people anyways?",
"invoke a student to take serious the word of",
"a teacher?",
"and yet pushes me so slightly away.",
"not the best but",
"it won’t kill you that fast.",
"we embrace and are passionate about?",
"delve deeper than what is",
"easy to say?",
"beautiful day",
"but this is you",
"and this is new",
"even that we want",
"text back some people",
"art",
"condition",
"for you",
"in structure and from falling apart",
"that is supposed to represent me",
"is a place I have always wanted to be",
"Grad students are our friendz",
"right now it's an acquaintance",
"flatten the hierarchy",
"everyone is your friend.",
"what about your brother/sister",
"i would like to try to be everyone's",
"brother and i would like to try",
"for everyone to be someone i cared for.",
"Yeah gotta fight for shit",
"to happen",
"What if I had",
"just gone to an art school",
"except for engagement",
"Go out and have some fun;",
"go out on a date,",
"with myself or with you,",
"I’m enjoying myself",
"If we can't date",
"Here now so I can do better",
"and be myself",
"And so it’s like,",
"not even enough time to breathe",
"and we receive all of this in life,",
"all that we never foresaw,",
"whether or not it is good or bad,",
"within seconds",
"when our words leave",
"our mouth we inherit all",
"that was contradictory to",
"what we assume",
"And so I wonder",
"what it is that",
"I have this peculiar luck",
"of the draw that neither is good nor bad.",
"A sort of good chance that",
"ends up always at odds with misfortune",
"Who do we decide to",
"extend our care",
"and concern toward?",
"Is the quest for love",
"hopelessly painful",
"and often fatal?",
"I want to learn",
"and teach",
"too late",
"In lieu of a",
"community we are born from,",
"we grow to make our own",
"PDF as",
"performance",
"Rethinking the value of an art",
"education/a new strategy for how",
"an art education is generally perceived",
"A bunch of hurt but",
"I was decided right here",
"How do I begin trusting",
"Google and how do I begin trusting",
"monopolies and",
"how do I begin trusting",
"I’m in outsider even in",
"the communities I belong to",
"The syllabus as",
"performance",
"First the web then the",
"app then the",
"My impression is that",
"many art galleries even today gravitate often to",
"I guess the more analog of digital;",
"CRT TVs, old Dells from the 80s.",
"I gravitate toward them too and",
"I’m not sure why",
"Even if I/we don’t intend for",
"what warrants it,",
"a tinge of jealousy always appears",
"when I am left for another",
"What’s the point of art",
"it feels there's too many",
"things to catch myself up on.",
"too many slack channels",
"A rush of melancholy sweeps through",
"In lieu of a community,",
"we create our own,",
"where we still don’t belong",
"Of concern and care",
"but instead I felt",
"profit, proprietary, and self-interest",
"I want to feel so grateful and to",
"trust",
"but you said “ya lol”",
"Even in my pursuit for",
"community so far there’s",
"someone who doesn’t",
"I am revisited but",
"no unfair nor agonizing pain comes with",
"this. I feel some melancholy",
"because nothing in the world would",
"have allowed me to have any",
"say in the final decision.",
"I had no control",
"no matter what",
"and it just happened because",
"circumstance decided it so.",
"Alignment of it all in place has",
"always been difficult and almost impossible.",
"And so I am unexpectedly revisted",
"and provided a fill of regret,",
"even though nothing I would have done",
"could justifiably make",
"me regretful.",
"Wait why do I care",
"the eclipse doesn't mind me.",
"for there is a hole in my chest anyways",
"I can’t even imagine",
"being remembered by you",
"but now you’re",
"having me remember you",
"I have a lot of life",
"to live so I'll be there",
"I don’t want to dream or",
"nightmare",
"I can’t help but hurt",
"Just what needs to be done",
"re: means regarding",
"It’s good to know people",
"The importance of .txt files",
"The importance of dot files",
"Is idolatry a sin?",
"All I want are mentors",
"In love?",
"That shit is insane",
"Content Management",
"Program Management",
"Knowledge Management",
"A feeling of defeat",
"a feeling of want",
"Who am I being saved for",
"And with that, the word",
"And with that, the truth",
"And with that, reality",
"For what I have given,",
"do I deserve",
"And yes, no one",
"Shit I do",
"for our department!!!!",
"No time to be denied",
"Least deserving, most receiving",
"Kinda bored",
"No one knows who I am.",
"Kinda neat",
"Someone stands by shyly.",
"They hope to join in",
"on this conversation you're in.",
"You invite them",
"maybe by saying",
"with earnest conern and consideration,",
"Oh would you like to",
"join in on our conversation?",
"Why am I full of tears",
"No one may mistreat me!",
"Will grad school",
"save you?",
"How do I take care",
"of myself",
"All I’ve could have been,",
"throw that out the window",
"I’ve fallen real hard",
"this time",
"but I think for good",
"Maybe the problem is",
"that people are attaching value",
"that may fundamentally not exist",
"but not even doing",
"the proper homework",
"to at least try",
"and make it exist",
"It’s okay",
"make something out of",
"nothing but not do your homework",
"and maybe that’s just it",
"people are not doing their homework ",
"Why is the pursuit for love",
"one you joke against?",
"Why aren’t you nice and",
"what did you do to deserve the best?",
"All I could ask for",
"It is a beautifully tragic thing to",
"be human",
"If we are not human",
"what is a better way to describe us",
"that also is inclusive",
"of our human ancestors?",
"Is there a term that",
"encapsulates all of that?",
"A lot of love",
"for someone who gives me a lot of stress",
"I’m making myself",
"believe that life is now too tragic",
"to have",
"Good old pain",
"It’s unfortunate",
"but it is",
"I need to go see Elephant Gym live now",
"Big fat crush"
};
